console.log("Hello, World!");

//npm -> Node Package Manager
// npm init -y -> Initializes a new Node.js project with default settings
//npm install package -> Installs a package from the npm registry


//package.json -> it includes the metadata about the project, such as name, version, description, main file, scripts, dependencies, and more.

//node_modules -> This directory contains all the installed packages and their dependencies. Each package has its own directory, which includes its code, metadata, and any dependencies it requires.

//package-lock.json -> This file is automatically generated when you install packages1. It locks the versions of the installed packages and their dependencies, ensuring that the same versions are used in future installations.


//npx -> Node Package Runner, a tool that allows you to run Node.js packages without installing them globally. It can execute packages directly from the npm registry or from your local node_modules directory.

//Example of using npx to run a package:
//npx create-vite@latest my-app